<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CatalogSeeder extends Seeder
{
    /**
     * Run the database seeds for categories and matching products.
     */
    public function run(): void
    {
        $categories = [
            [
                'id' => 1,
                'name' => 'Smartphones',
                'slug' => 'smartphones',
                'description' => 'Next-generation flagship smartphones with computational optics and all-day battery.',
                'image_url' => 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&auto=format&fit=crop&q=80',
                'is_active' => true,
            ],
            [
                'id' => 2,
                'name' => 'Laptops',
                'slug' => 'laptops',
                'description' => 'Precision ultrabooks and studio workstations engineered for creatives and engineers.',
                'image_url' => 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80',
                'is_active' => true,
            ],
            [
                'id' => 3,
                'name' => 'Audio',
                'slug' => 'audio',
                'description' => 'Acoustically tuned studio headphones and wireless earbuds with hybrid noise cancelling.',
                'image_url' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
                'is_active' => true,
            ],
            [
                'id' => 4,
                'name' => 'Wearables',
                'slug' => 'wearables',
                'description' => 'Advanced health monitors, GPS smartwatches, and minimalist fitness trackers.',
                'image_url' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
                'is_active' => true,
            ],
            [
                'id' => 5,
                'name' => 'Accessories',
                'slug' => 'accessories',
                'description' => 'Precision mechanical keyboards, ergonomic pointers, ultrawide displays, and desk essentials.',
                'image_url' => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
                'is_active' => true,
            ],
        ];

        foreach ($categories as $cat) {
            Category::updateOrCreate(['slug' => $cat['slug']], $cat);
        }

        $products = [
            // --- SMARTPHONES (Category ID: 1) ---
            [
                'id' => 1,
                'category_id' => 1,
                'name' => 'Aero Titan 5G Smartphone',
                'slug' => 'aero-titan-5g-smartphone',
                'sku' => 'PHN-ATN-001',
                'description' => 'Ultra-thin aerospace titanium chassis with 6.7-inch Super Retina XDR OLED display, 48MP pro triple-camera sensor, and 3nm neural engine.',
                'price' => 899.00,
                'stock_quantity' => 24,
                'image_url' => 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'id' => 2,
                'category_id' => 1,
                'name' => 'Nordic Horizon Fold 2',
                'slug' => 'nordic-horizon-fold-2',
                'sku' => 'PHN-NORD-002',
                'description' => 'Dual-screen foldable smartphone with seamless teardrop hinge, 120Hz dynamic AMOLED canvas, and desktop productivity mode.',
                'price' => 1299.00,
                'stock_quantity' => 12,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'id' => 3,
                'category_id' => 1,
                'name' => 'Pixelis Pure Ultra',
                'slug' => 'pixelis-pure-ultra',
                'sku' => 'PHN-PIX-003',
                'description' => 'Stock Android computational flagship with AI voice unblur, real-time live translation, and 50MP periscope zoom lens.',
                'price' => 799.00,
                'stock_quantity' => 18,
                'image_url' => 'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 4,
                'category_id' => 1,
                'name' => 'Zenith One Ceramic Edition',
                'slug' => 'zenith-one-ceramic-edition',
                'sku' => 'PHN-ZEN-004',
                'description' => 'Microcrystalline ceramic unibody with sapphire camera glass, 100W HyperCharge, and custom haptic vibration motors.',
                'price' => 949.00,
                'stock_quantity' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 5,
                'category_id' => 1,
                'name' => 'Vortex Pro Max Sapphire',
                'slug' => 'vortex-pro-max-sapphire',
                'sku' => 'PHN-VTX-005',
                'description' => 'Pro filmmaker powerhouse with 8K ProRes LOG recording, sensor-shift stabilization, and 1TB ultra-fast NVMe storage.',
                'price' => 1099.00,
                'stock_quantity' => 10,
                'image_url' => 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 6,
                'category_id' => 1,
                'name' => 'Quantum Edge Slate',
                'slug' => 'quantum-edge-slate',
                'sku' => 'PHN-QTM-006',
                'description' => 'Curved waterfall edge glass with 144Hz refresh rate, Dolby Vision HDR certification, and dual stereo speakers.',
                'price' => 699.00,
                'stock_quantity' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 7,
                'category_id' => 1,
                'name' => 'Helios Compact Mini',
                'slug' => 'helios-compact-mini',
                'sku' => 'PHN-HLS-007',
                'description' => 'Ergonomic 5.4-inch pocket-sized flagship with zero compromises on battery life, 5G speeds, or water resistance.',
                'price' => 549.00,
                'stock_quantity' => 22,
                'image_url' => 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 8,
                'category_id' => 1,
                'name' => 'Prism Optical Phone 14',
                'slug' => 'prism-optical-phone-14',
                'sku' => 'PHN-PRS-008',
                'description' => 'Dedicated macro and night photography sensor tuned in collaboration with German optical engineers.',
                'price' => 849.00,
                'stock_quantity' => 16,
                'image_url' => 'https://images.unsplash.com/photo-1567581935884-3349723552ca?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 9,
                'category_id' => 1,
                'name' => 'Eclipse Carbon Matte Phone',
                'slug' => 'eclipse-carbon-matte-phone',
                'sku' => 'PHN-ECL-009',
                'description' => 'Stealth matte textured glass back with zero fingerprint glare, vapor chamber cooling, and low latency 5G antennas.',
                'price' => 749.00,
                'stock_quantity' => 19,
                'image_url' => 'https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 10,
                'category_id' => 1,
                'name' => 'Solstice Studio Pro Max',
                'slug' => 'solstice-studio-pro-max',
                'sku' => 'PHN-SLS-010',
                'description' => 'Enterprise mobile powerhouse with hardware cryptographic vault, dual SIM + eSIM, and 5-year guaranteed security patches.',
                'price' => 1199.00,
                'stock_quantity' => 14,
                'image_url' => 'https://images.unsplash.com/photo-1616348436168-de43ad0db179?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],

            // --- LAPTOPS (Category ID: 2) ---
            [
                'id' => 11,
                'category_id' => 2,
                'name' => 'Apex Ultrabook 14 Pro',
                'slug' => 'apex-ultrabook-14-pro',
                'sku' => 'LPT-APX-011',
                'description' => 'Featherweight 14-inch OLED laptop with 120Hz refresh rate, 32GB unified RAM, and 18-hour battery in ceramic aluminum.',
                'price' => 1299.00,
                'stock_quantity' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'id' => 12,
                'category_id' => 2,
                'name' => 'Krona Air Carbon Ultralight',
                'slug' => 'krona-air-carbon-ultralight',
                'sku' => 'LPT-KRN-012',
                'description' => 'Under 1kg magnesium-carbon chassis with fanless whisper-quiet architecture, Thunderbolt 4, and edge-to-edge backlit keys.',
                'price' => 1149.00,
                'stock_quantity' => 18,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'id' => 13,
                'category_id' => 2,
                'name' => 'StudioBook 16 Studio Edition',
                'slug' => 'studiobook-16-studio-edition',
                'sku' => 'LPT-STU-013',
                'description' => 'Calibrated 4K color-accurate DCI-P3 display with discrete graphics, SD Express 7.0 slot, and dual fans with liquid metal cooling.',
                'price' => 1899.00,
                'stock_quantity' => 9,
                'image_url' => 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 14,
                'category_id' => 2,
                'name' => 'Zenith Blade Creator Laptop',
                'slug' => 'zenith-blade-creator-laptop',
                'sku' => 'LPT-ZBL-014',
                'description' => 'Engineered for video editors and 3D animators with high-TGP RTX GPU, 64GB DDR5 memory, and mechanical scissor-switch keys.',
                'price' => 1649.00,
                'stock_quantity' => 11,
                'image_url' => 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 15,
                'category_id' => 2,
                'name' => 'Vector Stealth Gaming Laptop',
                'slug' => 'vector-stealth-gaming-laptop',
                'sku' => 'LPT-VEC-015',
                'description' => 'High-performance QHD 240Hz screen, per-key RGB lighting, vapor chamber cooling, and Wi-Fi 7 ultra-low latency card.',
                'price' => 1999.00,
                'stock_quantity' => 8,
                'image_url' => 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 16,
                'category_id' => 2,
                'name' => 'Minimalist PureBook Air',
                'slug' => 'minimalist-purebook-air',
                'sku' => 'LPT-MNP-016',
                'description' => 'Sleek Scandinavian aesthetic with anti-glare IPS display, haptic glass trackpad, and recycled aluminum unibody.',
                'price' => 999.00,
                'stock_quantity' => 21,
                'image_url' => 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 17,
                'category_id' => 2,
                'name' => 'Hyperion OLED Developer Workstation',
                'slug' => 'hyperion-oled-developer-workstation',
                'sku' => 'LPT-HYP-017',
                'description' => 'Certified Linux & Windows developer edition with 16-core CPU, 2TB PCIe Gen4 SSD, and deep-travel tactile keyboard.',
                'price' => 2199.00,
                'stock_quantity' => 6,
                'image_url' => 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 18,
                'category_id' => 2,
                'name' => 'Astral Titanium 15 Book',
                'slug' => 'astral-titanium-15-book',
                'sku' => 'LPT-AST-018',
                'description' => '15.6-inch balanced everyday workstation with fast charging 99.9Wh flight-safe battery and quad speakers.',
                'price' => 1499.00,
                'stock_quantity' => 14,
                'image_url' => 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 19,
                'category_id' => 2,
                'name' => 'AeroSlate Convertible 2-in-1',
                'slug' => 'aeroslate-convertible-2-in-1',
                'sku' => 'LPT-ASL-019',
                'description' => '360-degree precision hinge with active pressure-sensitive stylus support for digital illustration and handwritten notes.',
                'price' => 1099.00,
                'stock_quantity' => 17,
                'image_url' => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 20,
                'category_id' => 2,
                'name' => 'Nexus Infinity Book 13',
                'slug' => 'nexus-infinity-book-13',
                'sku' => 'LPT-NXI-020',
                'description' => 'Ultra-compact 13.3-inch laptop designed for travel, remote meetings, and all-day coffee shop coding sessions.',
                'price' => 899.00,
                'stock_quantity' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],

            // --- AUDIO (Category ID: 3) ---
            [
                'id' => 21,
                'category_id' => 3,
                'name' => 'Aura Acoustic Wireless Headphones',
                'slug' => 'aura-acoustic-wireless-headphones',
                'sku' => 'AUD-AUR-021',
                'description' => 'Acoustically tuned studio headphones with 45dB adaptive active noise cancellation, custom 40mm biocellulose drivers, and spatial audio.',
                'price' => 299.00,
                'stock_quantity' => 25,
                'image_url' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'id' => 22,
                'category_id' => 3,
                'name' => 'Soniq Pure Studio Over-Ear',
                'slug' => 'soniq-pure-studio-over-ear',
                'sku' => 'AUD-SON-022',
                'description' => 'Open-back audiophile reference headphones delivering a neutral frequency curve and expansive natural soundstage.',
                'price' => 249.00,
                'stock_quantity' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'id' => 23,
                'category_id' => 3,
                'name' => 'AirPulse Noise-Canceling Earbuds',
                'slug' => 'airpulse-noise-canceling-earbuds',
                'sku' => 'AUD-ARP-023',
                'description' => 'Ergonomic in-ear wireless monitors with transparency mode, wireless Qi charging, IPX7 water resistance, and beamforming microphones.',
                'price' => 179.00,
                'stock_quantity' => 35,
                'image_url' => 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 24,
                'category_id' => 3,
                'name' => 'MasterTrack ANC Hi-Fi Headset',
                'slug' => 'mastertrack-anc-hi-fi-headset',
                'sku' => 'AUD-MST-024',
                'description' => 'Premium lambskin leather ear cushions, aircraft-grade aluminum arms, and lossless USB-C audio DAC support.',
                'price' => 349.00,
                'stock_quantity' => 16,
                'image_url' => 'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 25,
                'category_id' => 3,
                'name' => 'SoundSphere Minimalist Speaker',
                'slug' => 'soundsphere-minimalist-speaker',
                'sku' => 'AUD-SSP-025',
                'description' => '360-degree omnidirectional room-filling audio with AirPlay 2, Spotify Connect, and acoustic room tuning.',
                'price' => 129.00,
                'stock_quantity' => 28,
                'image_url' => 'https://images.unsplash.com/photo-1545127398-14699f92334b?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 26,
                'category_id' => 3,
                'name' => 'EchoBeam Portable Rugged Speaker',
                'slug' => 'echobeam-portable-rugged-speaker',
                'sku' => 'AUD-ECH-026',
                'description' => 'Shockproof, dustproof, and submersible IP68 speaker with 24 hours of playtime and built-in power bank.',
                'price' => 149.00,
                'stock_quantity' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 27,
                'category_id' => 3,
                'name' => 'PodPro True Wireless Buds',
                'slug' => 'podpro-true-wireless-buds',
                'sku' => 'AUD-PDP-027',
                'description' => 'Featherweight 4g earbuds with customizable EQ profiles, pressure-relief vents, and ultra-compact pocket case.',
                'price' => 159.00,
                'stock_quantity' => 40,
                'image_url' => 'https://images.unsplash.com/photo-1598331668826-20cecc596b86?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 28,
                'category_id' => 3,
                'name' => 'Krona SoundDock Home Speaker',
                'slug' => 'krona-sounddock-home-speaker',
                'sku' => 'AUD-KSD-028',
                'description' => 'Dual subwoofers with fabric grille, multi-room sync, and touch controls for audiophile domestic listening.',
                'price' => 199.00,
                'stock_quantity' => 19,
                'image_url' => 'https://images.unsplash.com/photo-1577174881658-0f30ed549adc?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 29,
                'category_id' => 3,
                'name' => 'Nordic Reverberation Soundbar',
                'slug' => 'nordic-reverberation-soundbar',
                'sku' => 'AUD-NRV-029',
                'description' => 'Dolby Atmos home cinema soundbar with integrated upfiring height channels and eARC HDMI connectivity.',
                'price' => 279.00,
                'stock_quantity' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1543512214-318c7553f230?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 30,
                'category_id' => 3,
                'name' => 'StudioWave Broadcast Microphone',
                'slug' => 'studiowave-broadcast-microphone',
                'sku' => 'AUD-STW-030',
                'description' => 'Cardioid condenser studio microphone with built-in pop filter, shock mount, and zero-latency headphone monitoring.',
                'price' => 189.00,
                'stock_quantity' => 22,
                'image_url' => 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],

            // --- WEARABLES (Category ID: 4) ---
            [
                'id' => 31,
                'category_id' => 4,
                'name' => 'Apex Pulse Smartwatch Series 8',
                'slug' => 'apex-pulse-smartwatch-series-8',
                'sku' => 'WRB-APX-031',
                'description' => 'Sleek aluminum smartwatch featuring continuous ECG, optical heart rate sensor, sapphire crystal touchscreen, and 4-day battery.',
                'price' => 299.00,
                'stock_quantity' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'id' => 32,
                'category_id' => 4,
                'name' => 'Vanguard Titanium Chrono',
                'slug' => 'vanguard-titanium-chrono',
                'sku' => 'WRB-VNG-032',
                'description' => 'Rugged grade-5 titanium outdoor adventure smartwatch with multi-band GPS, 100m depth gauge, and solar expedition battery.',
                'price' => 399.00,
                'stock_quantity' => 14,
                'image_url' => 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'id' => 33,
                'category_id' => 4,
                'name' => 'Lumina Fitness Loop Band',
                'slug' => 'lumina-fitness-loop-band',
                'sku' => 'WRB-LMN-033',
                'description' => 'Screenless distraction-free fitness band measuring skin temperature, recovery strain, and sleep cycles with 7-day battery.',
                'price' => 99.00,
                'stock_quantity' => 45,
                'image_url' => 'https://images.unsplash.com/photo-1510017803434-a899398421b3?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 34,
                'category_id' => 4,
                'name' => 'Terra Sport GPS Watch',
                'slug' => 'terra-sport-gps-watch',
                'sku' => 'WRB-TR-034',
                'description' => 'Trail runner and marathon watch with offline topographic maps, barometric altimeter, and VO2 max estimation.',
                'price' => 329.00,
                'stock_quantity' => 16,
                'image_url' => 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 35,
                'category_id' => 4,
                'name' => 'Krona Minimalist Matte Watch',
                'slug' => 'krona-minimalist-matte-watch',
                'sku' => 'WRB-KRN-035',
                'description' => 'Hybrid analog-digital smartwatch with physical luminous hands over a discrete e-ink notification layer.',
                'price' => 189.00,
                'stock_quantity' => 25,
                'image_url' => 'https://images.unsplash.com/photo-1509741102003-ca64bfe5f069?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 36,
                'category_id' => 4,
                'name' => 'BioTrack Health & Sleep Tracker',
                'slug' => 'biotrack-health-sleep-tracker',
                'sku' => 'WRB-BIO-036',
                'description' => 'Continuous SpO2 blood oxygen monitoring, stress resilience scores, and vibrating smart morning wake alarms.',
                'price' => 139.00,
                'stock_quantity' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1544117519-31a4b719223d?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 37,
                'category_id' => 4,
                'name' => 'Aero Active Sport Smartwatch',
                'slug' => 'aero-active-sport-smartwatch',
                'sku' => 'WRB-AER-037',
                'description' => 'Lightweight silicone sport band with 50+ workout modes, automatic rep counting, and onboard music storage.',
                'price' => 219.00,
                'stock_quantity' => 22,
                'image_url' => 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 38,
                'category_id' => 4,
                'name' => 'Vitalis ECG Heart Monitor Watch',
                'slug' => 'vitalis-ecg-heart-monitor-watch',
                'sku' => 'WRB-VIT-038',
                'description' => 'Clinical accuracy AFib detection with PDF cardiac reports directly exportable to your healthcare provider.',
                'price' => 259.00,
                'stock_quantity' => 18,
                'image_url' => 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 39,
                'category_id' => 4,
                'name' => 'Horizon Steel Ceramic Smartwatch',
                'slug' => 'horizon-steel-ceramic-smartwatch',
                'sku' => 'WRB-HRZ-039',
                'description' => 'Polished 316L stainless steel casing with ceramic bezel, interchangeable links, and contactless payment NFC.',
                'price' => 349.00,
                'stock_quantity' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 40,
                'category_id' => 4,
                'name' => 'Onyx Ring Sleep & Recovery',
                'slug' => 'onyx-ring-sleep-recovery',
                'sku' => 'WRB-ONX-040',
                'description' => 'Ultralight titanium smart ring worn comfortably on your finger, tracking heart rate variability, sleep stages, and readiness.',
                'price' => 279.00,
                'stock_quantity' => 25,
                'image_url' => 'https://images.unsplash.com/photo-1516542076529-1ea3854896f2?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],

            // --- ACCESSORIES (Category ID: 5) ---
            [
                'id' => 41,
                'category_id' => 5,
                'name' => 'Linear Pro Mechanical Keyboard',
                'slug' => 'linear-pro-mechanical-keyboard',
                'sku' => 'ACC-LKB-041',
                'description' => 'Gasket-mounted 75% mechanical keyboard with hot-swappable factory-lubed linear switches and double-shot PBT keycaps.',
                'price' => 159.00,
                'stock_quantity' => 28,
                'image_url' => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'id' => 42,
                'category_id' => 5,
                'name' => 'Glide Ergo Precision Wireless Mouse',
                'slug' => 'glide-ergo-precision-wireless-mouse',
                'sku' => 'ACC-GER-042',
                'description' => 'Sculpted vertical ergonomic mouse with thumb scroll wheel, optical sensor up to 4000 DPI, and multi-device Bluetooth pairing.',
                'price' => 89.00,
                'stock_quantity' => 35,
                'image_url' => 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'id' => 43,
                'category_id' => 5,
                'name' => 'ViewMaster 34" Curved Ultrawide',
                'slug' => 'viewmaster-34-curved-ultrawide',
                'sku' => 'ACC-VMW-043',
                'description' => 'WQHD 1800R curved monitor with 99% sRGB color gamut, USB-C 90W single-cable power delivery, and KVM switch.',
                'price' => 649.00,
                'stock_quantity' => 10,
                'image_url' => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 44,
                'category_id' => 5,
                'name' => 'MultiPort Thunderbolt 4 Dock',
                'slug' => 'multiport-thunderbolt-4-dock',
                'sku' => 'ACC-MTB-044',
                'description' => '12-in-1 workstation hub featuring dual 4K 60Hz display outputs, 2.5GbE Ethernet, 100W laptop charging, and UHS-II card reader.',
                'price' => 199.00,
                'stock_quantity' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1629429408209-1f912961dbd8?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 45,
                'category_id' => 5,
                'name' => 'MagCharge Qi2 Wireless Stand',
                'slug' => 'magcharge-qi2-wireless-stand',
                'sku' => 'ACC-MGC-045',
                'description' => 'Magnetic 15W fast wireless charging stand crafted from solid milled aluminum with floating orientation for standby mode.',
                'price' => 69.00,
                'stock_quantity' => 40,
                'image_url' => 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 46,
                'category_id' => 5,
                'name' => 'AeroRise Aluminum Laptop Stand',
                'slug' => 'aerorise-aluminum-laptop-stand',
                'sku' => 'ACC-ARS-046',
                'description' => 'Elevates your laptop screen to eye level for optimal ergonomic posture with silicone protective pads and open airflow.',
                'price' => 49.00,
                'stock_quantity' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 47,
                'category_id' => 5,
                'name' => 'Volta 100W GaN Fast Charger',
                'slug' => 'volta-100w-gan-fast-charger',
                'sku' => 'ACC-VLT-047',
                'description' => 'Pocket-sized gallium nitride power brick with triple USB-C ports capable of charging a laptop, tablet, and phone simultaneously.',
                'price' => 59.00,
                'stock_quantity' => 45,
                'image_url' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 48,
                'category_id' => 5,
                'name' => 'Walnut & Aluminum Headphone Stand',
                'slug' => 'walnut-aluminum-headphone-stand',
                'sku' => 'ACC-WHS-048',
                'description' => 'Handcrafted solid North American walnut cradle atop a bead-blasted silver aluminum stem with non-slip base.',
                'price' => 45.00,
                'stock_quantity' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 49,
                'category_id' => 5,
                'name' => 'Nexus PowerBank 24,000mAh',
                'slug' => 'nexus-powerbank-24000mah',
                'sku' => 'ACC-NPB-049',
                'description' => 'High-capacity airline-approved battery pack with 140W bidirectional PD 3.1 and smart OLED real-time wattage display.',
                'price' => 89.00,
                'stock_quantity' => 32,
                'image_url' => 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'id' => 50,
                'category_id' => 5,
                'name' => 'LumiDesk ScreenBar Monitor Light',
                'slug' => 'lumidesk-screenbar-monitor-light',
                'sku' => 'ACC-LDS-050',
                'description' => 'Asymmetric optical light bar that clips atop any monitor, eliminating screen glare with auto-dimming ambient sensor and wireless rotary dial.',
                'price' => 79.00,
                'stock_quantity' => 35,
                'image_url' => 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&auto=format&fit=crop&q=80',
                'is_active' => true,
                'is_featured' => false,
            ],
        ];

        foreach ($products as $prod) {
            Product::updateOrCreate(['id' => $prod['id']], $prod);
        }

        // Align PostgreSQL sequences after explicit id inserts
        if (\Illuminate\Support\Facades\DB::connection()->getDriverName() === 'pgsql') {
            foreach (['categories', 'products'] as $table) {
                $seq = \Illuminate\Support\Facades\DB::selectOne("SELECT pg_get_serial_sequence('{$table}', 'id') as seq");
                if ($seq && $seq->seq) {
                    \Illuminate\Support\Facades\DB::statement("SELECT setval('{$seq->seq}', COALESCE((SELECT MAX(id) FROM {$table}), 0) + 1, false)");
                }
            }
        }
    }
}
